### ISSUE TITLE
Hi Marcio ✋ Can you please add good documentation? 😀

### ISSUE THREAD

**Issue by abuzarmushtaq** [MarcioQuimbundo/uber_clone#1]

**Comment by MarcioQuimbundo** [comment]
Hi abuza, comming soon.

Thanks

**Comment by abuzarmushtaq** [comment]
Okay, abuzar* 😄

**Comment by Hawaiideveloper** [comment]
Looks like the README.md for client  is located at: https://github.com/MarcioQuimbundo/uber_clone/blob/master/uber_rider/README.md

Looks like the README.md for driver is located at: https://github.com/MarcioQuimbundo/uber_clone/tree/master/uber_driver

If you have further questions it would be best asked in regards to objects.

**Comment by Hawaiideveloper** [comment]
Let me know if the top two links are useful if so, I will contribute more to your project.

---edit--
I was thinking in Spanish
