### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gatarelib** [MarcioQuimbundo/uber_clone#2]
Would be nice if you had good documentation

**Comment by MarcioQuimbundo** [comment]
comming soon

**Comment by Hawaiideveloper** [comment]
duplicate

**Comment by Hawaiideveloper** [comment]
This issue resembles this one


https://github.com/MarcioQuimbundo/uber_clone/issues/4

**Comment by Hawaiideveloper** [comment]
Issue is duplicate of this one:
https://github.com/MarcioQuimbundo/uber_clone/issues/1
