### ISSUE TITLE
Request to add Licence

### ISSUE THREAD

**Issue by maheshwari-1153** [MarcioQuimbundo/uber_clone#3]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.
Let me know if you are interested showcase your product in our open source website. If yes, then I request you to add MIT Licence in your repo.
Looking forward to hear from you.

**Comment by MarcioQuimbundo** [comment]
Hi @maheshwari-1153 , I added the  MIT Licence in my repo, now u can add to your website

**Comment by maheshwari-1153** [comment]
Hello,

Thanks for informing me. I will check & let you know.

Best Regards,
Maheshwari Shukla
