### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by EloneSampaio** [MarcioQuimbundo/uber_clone#4]
hi brother have any documentation ???

**Comment by Hawaiideveloper** [comment]
Looks like the update came from here:
https://github.com/MarcioQuimbundo/uber_clone/issues/2#issuecomment-491801948

**Comment by Hawaiideveloper** [comment]
duplicate

**Comment by Hawaiideveloper** [comment]
I posted documentation on it here

https://github.com/MarcioQuimbundo/uber_clone/issues/1#issuecomment-545033360

**Comment by Hawaiideveloper** [comment]
please comment and let me know if we can close this issue

**Comment by Hawaiideveloper** [comment]
Issue is cloned by this one:

https://github.com/MarcioQuimbundo/uber_clone/issues/1
