### ISSUE TITLE
App only white screen

### ISSUE THREAD

**Issue by rkg0612** [MarcioQuimbundo/uber_clone#5]
Hi, 

I cloned the app and it only returned white screen. What's the problem? Thanks!

**Comment by a-k-o-r-e-d-e** [comment]
I experienced this too. i had to put 'WidgetsFlutterBinding.ensureInitialized()' as the first line before runApp() in main.dart

**Comment by rkg0612** [comment]
> I experienced this too. i had to put 'WidgetsFlutterBinding.ensureInitialized()' as the first line before runApp() in main.dart

Any reason behind the app not running except put the snippet you suggested? I just got it to run after I put that snippet before runApp()

**Comment by jahkid** [comment]
> Hi,
> 
> I cloned the app and it only returned white screen. What's the problem? Thanks!

please im getting a number of errors and there isnt any documentations, can you help me with how u managed to get the app running?

**Comment by felipecastrosales** [comment]
I also have this problem, how did you solve it?

**Comment by felipecastrosales** [comment]
> I experienced this too. i had to put 'WidgetsFlutterBinding.ensureInitialized()' as the first line before runApp() in main.dart

Where?

**Comment by felipecastrosales** [comment]
> > Hi,
> > I cloned the app and it only returned white screen. What's the problem? Thanks!
> 
> please im getting a number of errors and there isnt any documentations, can you help me with how u managed to get the app running?

In terminal put flutter pub get, but it will still have some problems

**Comment by a-k-o-r-e-d-e** [comment]
> > I experienced this too. i had to put 'WidgetsFlutterBinding.ensureInitialized()' as the first line before runApp() in main.dart
> 
> Where?

In your main.dart file. It has to come before the runApp(); line

**Comment by felipecastrosales** [comment]
I still haven't succeeded, could you show me better?

**Comment by felipecastrosales** [comment]
> In your main.dart file. It has to come before the runApp(); line

I still haven't succeeded, could you show me better?

**Comment by a-k-o-r-e-d-e** [comment]
Hey Felipe, I don't think i can help much if I don't see your error messages. Try to post the error logs and I'll try to help as much as I can

**Comment by felipecastrosales** [comment]
Hi, Lone.
![image](https://user-images.githubusercontent.com/59374587/98813347-c646df00-2402-11eb-990d-34d81400b293.png)
This is my errors.
There are no more problems with the codes, but it still doesn't appear on the map, as it is in the demo in the README

**Comment by mohammadalshawish** [comment]
![image](https://user-images.githubusercontent.com/28256560/109349749-1dbc6e00-787f-11eb-9259-4aca77c479ed.png)
I Have this error

**Comment by muhibbin-munna** [comment]
> 
> 
> > In your main.dart file. It has to come before the runApp(); line
> 
> I still haven't succeeded, could you show me better?

did you find any solution to this?
